---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: winrm
  gather_facts: no
  vars_files: vars/windows.yml
  tasks:
    - name: Whoami
      ansible.windows.win_command:
        cmd: 'whoami'
        chdir: 'C:\'
      ignore_errors: true

    - name: ll EE
      ansible.builtin.command: ls -la /tmp/
      register: myls
      delegate_to: localhost
      vars:
        ansible_connection: local
        ansible_port: 22

    - name: Copying from Ansible to Windows local disk
      ansible.windows.win_copy:
        src: "/tmp/{{ smart_console_exe }}"
        dest: 'C:\Windows\Temp\'
        remote_src: False
        force: True
      ignore_errors: true

    - name: Install exe file
      ansible.windows.win_package:
        path: C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe
        arguments: /install /passive /norestart
      ignore_errors: true
