---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Change Checkpoint password
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

  # cat private-key.pem | ansible-vault encrypt_string  --stdin-name 'private_key' --output private-key.vault
  - ansible.builtin.include_vars: files/private-key.yml

  - name: Copy private key locally
    ansible.builtin.copy:
      content: "{{ private_key }}"
      dest: /tmp/private-key.pem
      mode: '0600'

  # https://docs.paloaltonetworks.com/vm-series/11-1/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/deploy-the-vm-series-firewall-on-aws/launch-the-vm-series-firewall-on-aws
  - name: Set admin initial password
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem admin@{{ groups['paloalto'][0] }}"
      responses:
        # In order to configure your system, please access the Web UI and finish the First Time Wizard.
        # i-047b52cf6b7891b2c> set user admin password
        # New password:
        # Verify new password:
        # i-047b52cf6b7891b2c>
        'i-':
          - "set user admin password"
          - exit
        'New password:':
          - "{{ new_password }}" 
        'Verify new password:':
          - "{{ new_password }}"
    no_log: false # hide passwords on logs
