---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Change Checkpoint password
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

  # cat private-key.pem | ansible-vault encrypt_string  --stdin-name 'private_key' --output private-key.vault
  - ansible.builtin.include_vars: files/private-key.yml

  - name: Copy private key locally
    ansible.builtin.copy:
      content: "{{ private_key }}"
      dest: /tmp/private-key.pem
      mode: '0600'

  # https://community.checkpoint.com/t5/Cloud-Network-Security/CloudGuard-Network-security-default-password/td-p/201985
  - name: Set admin initial password
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem admin@{{ groups['checkpoint'][0] }}"
      # echo: true
      responses:
        # In order to configure your system, please access the Web UI and finish the First Time Wizard.
        # set user admin password
        # i-047b52cf6b7891b2c> set user admin password-hash {{ new_password | password_hash('md5') }}
        'i-.*>':
          - "set user admin password-hash {{ new_password | password_hash('md5') }}"
          - "set expert-password-hash {{ new_password | password_hash('md5') }}"
          - expert
          - save config
          - exit
        "Expert":
          - "config_system --config-string \"hostname=myhost&domainname=somedomain.com&timezone='America/Indiana/Indianapolis'&ftw_sic_key=aaaa&install_security_gw=true&gateway_daip=false&install_ppak=true&gateway_cluster_member=true&install_security_managment=false&maintenance_hash=123456\""
          - exit
          # - 'mgmt_cli -r true --domain MDS set api-settings accepted-api-calls-from "All IP addresses"'
          # - api restart
        # 'New password':
        #   - "{{ new_password }}" 
        # 'Verify new password':
        #   - "{{ new_password }}"
        "(?i)Enter expert password":
          - "{{ new_password }}" 
    no_log: false # hide passwords on logs
