---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Firewalls Checkpoint
  hosts: "{{ groups['checkpoint'][0] }}"
  connection: httpapi
  gather_facts: no
  roles:
    - checkpoint_policy_rules
