---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: winrm
  gather_facts: no
  vars_files: vars/windows.yml
  tasks:
    - name: Check SmartConsole exe in the EE
      ansible.builtin.command: ls -la "/tmp/{{ smart_console_exe }}"
      register: myls
      delegate_to: localhost
      vars:
        ansible_connection: local
        ansible_port: 22

    - name: Decompress exe file
      community.windows.win_unzip:
        src: 'C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe'
        dest: 'C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole2\'

    # - name: Copying from Ansible to Windows local disk
    #   ansible.windows.win_copy:
    #     src: "/tmp/{{ smart_console_exe }}"
    #     dest: 'C:\Windows\Temp\'
    #     remote_src: False
    #     force: True
    #   vars:
    #     ansible_winrm_operation_timeout_sec: 1500
    #     ansible_winrm_read_timeout_sec: 1800

    # - name: Install exe file (win_package)
    #   ansible.windows.win_package:
    #     path: 'C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe'
    #     arguments: -s
    #     state: present
    #   vars:
    #     ansible_winrm_operation_timeout_sec: 1500
    #     ansible_winrm_read_timeout_sec: 1800

    # - name: Install exe file (command)
    #   ansible.windows.win_command:
    #     cmd: 'C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe -s'
    #     chdir: C:\Windows\TEMP

    # - name: Install exe file (powershell)
    #   ansible.windows.win_powershell:
    #     script: 'C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe -s'
