---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  vars:
    ansible_user: Administrator
    ansible_ssh_pass: "{{ new_password }}"
  tasks:

    - debug:
        msg: "{{ groups['windows'][0] }}"

    - name: Copying from Ansible to Windows local disk
      ansible.windows.win_copy:
        src: /tmp/Check_Point_R81.20_T631_SmartConsole.exe
        dest: C:\
        remote_src: yes
        force: True
      # become: True

    - name: Install exe file
      ansible.windows.win_package:
        path: C:\Check_Point_R81.20_T631_SmartConsole.exe
        arguments: /install /passive /norestart
