---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: winrm
  gather_facts: no
  vars_files: vars/windows.yml
  tasks:
    - name: Check SmartConsole exe in the EE
      ansible.builtin.command: ls -la "/tmp/{{ smart_console_installer }}.exe"
      register: myls
      delegate_to: localhost
      vars:
        ansible_connection: local
        ansible_port: 22

    - name: Copying from Ansible to Windows local disk
      ansible.windows.win_copy:
        src: "/tmp/{{ smart_console_installer }}.exe"
        dest: 'C:\Windows\Temp\'
        remote_src: False
        force: True

    - name: Dir C:\Windows\Temp\ folder
      ansible.windows.win_shell: dir
      args:
        chdir: 'C:\Windows\Temp'
        executable: cmd

    - name: Install WinRAR with chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: WinRAR
        state: present

    - name: Dir C:\Program files\WinRAR folder
      args:
      ansible.windows.win_shell: dir
      args:
        chdir: 'C:\Program files\WinRAR'
        executable: cmd

    - name: Extract files from exe installer package
      ansible.windows.win_command:
        cmd: "\"C:\\Program Files\\WinRAR\\WinRAR.exe\" x {{ smart_console_installer }}.exe {{ smart_console_installer }}\\ -IBCK"
        chdir: 'C:\Windows\Temp'

    - name: Install VC++ from vcredist_x86.exe file
      ansible.windows.win_command:
        cmd: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\vc11\vcredist_x86.exe /s"
        chdir: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\vc11"

    - name: Install VC++ from vc_redist.x86_vs2017.exe file
      ansible.windows.win_command:
        cmd: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\vc17\\vc_redist.x86_vs2017.exe /s"
        chdir: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\vc17"

    - name: Install SmartConsole from SmartConsole.exe file
      ansible.windows.win_command:
        cmd: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\SmartConsole.exe /s"
        chdir: "C:\\Windows\\Temp\\{{ smart_console_installer }}\\"
