---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: winrm
  gather_facts: no
  #vars_files: vars/main.yml
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:

    - debug:
        msg: "{{ groups['windows'][0] }}"

    - name: Ping
      ansible.windows.win_ping:

    - name: Whoami
      ansible.windows.win_command:
        cmd: 'whoami'
        chdir: 'C:\'
      ignore_errors: true

    - name: ll EE
      ansible.builtin.command: ls -la /tmp/
      register: myls
      delegate_to: localhost
      vars:
        ansible_connection: local
        ansible_port: 22

    - name: Copying from Ansible to Windows local disk
      ansible.windows.win_copy:
        src: /tmp/Check_Point_R81.20_T631_SmartConsole.exe
        dest: 'C:\Windows\Temp\'
        remote_src: False
        force: True
      ignore_errors: true

    - name: Install exe file
      ansible.windows.win_package:
        path: C:\Windows\Temp\Check_Point_R81.20_T631_SmartConsole.exe
        arguments: /install /passive /norestart
      ignore_errors: true
