---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Firewalls Checkpoint
  hosts: "{{ groups['checkpoint'][0] }}"
  connection: httpapi
  ansible_network_os: check_point.mgmt.checkpoint
  ansible_connection: httpapi
  ansible_httpapi_use_ssl: yes
  ansible_httpapi_validate_certs: no
  gather_facts: no
  roles:
    - checkpoint_policy_rules
