---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Windows
  hosts: "{{ groups['windows'][0] }}"
  connection: winrm
  gather_facts: no
  vars_files: vars/main.yml
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: "{{ new_password }}"
  tasks:

  # cat private-key.pem | ansible-vault encrypt_string  --stdin-name 'private_key' --output private-key.vault
    - ansible.builtin.include_vars: files/private-key.yml
      delegate_to: localhost

    # - name: get the Administrator password
    #   community.aws.ec2_win_password:
    #     instance_id: i-XXXXXX
    #     key_data: "{{ private_key }}"

    - debug:
        msg: "{{ groups['windows'][0] }}"

    - name: Ping
      ansible.windows.win_ping:

    - name: Dir
      ansible.windows.win_command:
        cmd: 'dir'
        chdir: 'C:\Windows\TEMP'

    - name: Copying from Ansible to Windows local disk
      ansible.windows.win_copy:
        src: /tmp/Check_Point_R81.20_T631_SmartConsole.exe
        dest: 'C:\Temp'
        remote_src: yes
        force: True
      # become: True

    - name: Install exe file
      ansible.windows.win_package:
        path: C:\Temp\Check_Point_R81.20_T631_SmartConsole.exe
        arguments: /install /passive /norestart
