# VPC
ec2_vpc_name: VPC1
ec2_vpc_region: us-east-1
ec2_vpc_cidr: 10.0.0.0/16
# Subnet
ec2_subnet_name: Subnet1
ec2_subnet_cidr: 10.0.0.0/24
# IGW
ec2_igw_name: IGW1
# Route Table
ec2_rt_name: RT1
# RHEL Open ports
ec2_sg_name: SG1
ec2_sg_openports:
  - 80
  - 443
  - 22
# AMI
#ec2_image_name: RHEL-8.6.0_HVM-*x86_64*
ec2_image_name: Check Point CloudGuard IaaS GW PAYG-NGTX R81.20-631.1291-5c2a3811-4da1-49e0-a2f9-b9a369548106
#ec2_image_name: ami-07662d6765aef154e
# Flavour 
ec2_flavor_name: c5.large
# Disk
ec2_disk_size: 20
ec2_ebs_name: /dev/sda1
# Key Pair
ec2_key_name: "KeyPair"
# Instance
ec2_instance_name: checkpoint-1
